// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COLUMNNUM_ROCKSDB_H_
#define FLATBUFFERS_GENERATED_COLUMNNUM_ROCKSDB_H_

#include "flatbuffers/flatbuffers.h"

namespace rocksdb {

struct FbColNum;

struct FbColNum FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_COL0 = 4,
    VT_COL1 = 6
  };
  uint32_t col0() const {
    return GetField<uint32_t>(VT_COL0, 0);
  }
  uint32_t col1() const {
    return GetField<uint32_t>(VT_COL1, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_COL0) &&
           VerifyField<uint32_t>(verifier, VT_COL1) &&
           verifier.EndTable();
  }
};

struct FbColNumBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_col0(uint32_t col0) {
    fbb_.AddElement<uint32_t>(FbColNum::VT_COL0, col0, 0);
  }
  void add_col1(uint32_t col1) {
    fbb_.AddElement<uint32_t>(FbColNum::VT_COL1, col1, 0);
  }
  explicit FbColNumBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  FbColNumBuilder &operator=(const FbColNumBuilder &);
  flatbuffers::Offset<FbColNum> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<FbColNum>(end);
    return o;
  }
};

inline flatbuffers::Offset<FbColNum> CreateFbColNum(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t col0 = 0,
    uint32_t col1 = 0) {
  FbColNumBuilder builder_(_fbb);
  builder_.add_col1(col1);
  builder_.add_col0(col0);
  return builder_.Finish();
}

inline const rocksdb::FbColNum *GetFbColNum(const void *buf) {
  return flatbuffers::GetRoot<rocksdb::FbColNum>(buf);
}

inline const rocksdb::FbColNum *GetSizePrefixedFbColNum(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<rocksdb::FbColNum>(buf);
}

inline bool VerifyFbColNumBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<rocksdb::FbColNum>(nullptr);
}

inline bool VerifySizePrefixedFbColNumBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<rocksdb::FbColNum>(nullptr);
}

inline void FinishFbColNumBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<rocksdb::FbColNum> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedFbColNumBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<rocksdb::FbColNum> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace rocksdb

#endif  // FLATBUFFERS_GENERATED_COLUMNNUM_ROCKSDB_H_
