// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COLUMNSTR_ROCKSDB_H_
#define FLATBUFFERS_GENERATED_COLUMNSTR_ROCKSDB_H_

#include "flatbuffers/flatbuffers.h"

namespace rocksdb {

struct FbColStr;

struct FbColStr FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_COL0 = 4,
    VT_COL1 = 6
  };
  const flatbuffers::String *col0() const {
    return GetPointer<const flatbuffers::String *>(VT_COL0);
  }
  const flatbuffers::String *col1() const {
    return GetPointer<const flatbuffers::String *>(VT_COL1);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_COL0) &&
           verifier.VerifyString(col0()) &&
           VerifyOffset(verifier, VT_COL1) &&
           verifier.VerifyString(col1()) &&
           verifier.EndTable();
  }
};

struct FbColStrBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_col0(flatbuffers::Offset<flatbuffers::String> col0) {
    fbb_.AddOffset(FbColStr::VT_COL0, col0);
  }
  void add_col1(flatbuffers::Offset<flatbuffers::String> col1) {
    fbb_.AddOffset(FbColStr::VT_COL1, col1);
  }
  explicit FbColStrBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  FbColStrBuilder &operator=(const FbColStrBuilder &);
  flatbuffers::Offset<FbColStr> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<FbColStr>(end);
    return o;
  }
};

inline flatbuffers::Offset<FbColStr> CreateFbColStr(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> col0 = 0,
    flatbuffers::Offset<flatbuffers::String> col1 = 0) {
  FbColStrBuilder builder_(_fbb);
  builder_.add_col1(col1);
  builder_.add_col0(col0);
  return builder_.Finish();
}

inline flatbuffers::Offset<FbColStr> CreateFbColStrDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *col0 = nullptr,
    const char *col1 = nullptr) {
  auto col0__ = col0 ? _fbb.CreateString(col0) : 0;
  auto col1__ = col1 ? _fbb.CreateString(col1) : 0;
  return rocksdb::CreateFbColStr(
      _fbb,
      col0__,
      col1__);
}

inline const rocksdb::FbColStr *GetFbColStr(const void *buf) {
  return flatbuffers::GetRoot<rocksdb::FbColStr>(buf);
}

inline const rocksdb::FbColStr *GetSizePrefixedFbColStr(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<rocksdb::FbColStr>(buf);
}

inline bool VerifyFbColStrBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<rocksdb::FbColStr>(nullptr);
}

inline bool VerifySizePrefixedFbColStrBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<rocksdb::FbColStr>(nullptr);
}

inline void FinishFbColStrBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<rocksdb::FbColStr> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedFbColStrBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<rocksdb::FbColStr> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace rocksdb

#endif  // FLATBUFFERS_GENERATED_COLUMNSTR_ROCKSDB_H_
