// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ROWNUM_ROCKSDB_H_
#define FLATBUFFERS_GENERATED_ROWNUM_ROCKSDB_H_

#include "flatbuffers/flatbuffers.h"

namespace rocksdb {

struct FbRowNum;

struct FbRowNum FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_COL = 4
  };
  const flatbuffers::Vector<int32_t> *col() const {
    return GetPointer<const flatbuffers::Vector<int32_t> *>(VT_COL);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_COL) &&
           verifier.VerifyVector(col()) &&
           verifier.EndTable();
  }
};

struct FbRowNumBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_col(flatbuffers::Offset<flatbuffers::Vector<int32_t>> col) {
    fbb_.AddOffset(FbRowNum::VT_COL, col);
  }
  explicit FbRowNumBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  FbRowNumBuilder &operator=(const FbRowNumBuilder &);
  flatbuffers::Offset<FbRowNum> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<FbRowNum>(end);
    return o;
  }
};

inline flatbuffers::Offset<FbRowNum> CreateFbRowNum(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<int32_t>> col = 0) {
  FbRowNumBuilder builder_(_fbb);
  builder_.add_col(col);
  return builder_.Finish();
}

inline flatbuffers::Offset<FbRowNum> CreateFbRowNumDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<int32_t> *col = nullptr) {
  auto col__ = col ? _fbb.CreateVector<int32_t>(*col) : 0;
  return rocksdb::CreateFbRowNum(
      _fbb,
      col__);
}

inline const rocksdb::FbRowNum *GetFbRowNum(const void *buf) {
  return flatbuffers::GetRoot<rocksdb::FbRowNum>(buf);
}

inline const rocksdb::FbRowNum *GetSizePrefixedFbRowNum(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<rocksdb::FbRowNum>(buf);
}

inline bool VerifyFbRowNumBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<rocksdb::FbRowNum>(nullptr);
}

inline bool VerifySizePrefixedFbRowNumBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<rocksdb::FbRowNum>(nullptr);
}

inline void FinishFbRowNumBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<rocksdb::FbRowNum> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedFbRowNumBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<rocksdb::FbRowNum> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace rocksdb

#endif  // FLATBUFFERS_GENERATED_ROWNUM_ROCKSDB_H_
