// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ROW_ROCKSDB_H_
#define FLATBUFFERS_GENERATED_ROW_ROCKSDB_H_

#include "flatbuffers/flatbuffers.h"

namespace rocksdb {

struct FbRow;

struct FbRow FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NUMCOLS = 4,
    VT_STRCOLS = 6
  };
  const flatbuffers::Vector<int32_t> *numcols() const {
    return GetPointer<const flatbuffers::Vector<int32_t> *>(VT_NUMCOLS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *strcols() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(VT_STRCOLS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NUMCOLS) &&
           verifier.VerifyVector(numcols()) &&
           VerifyOffset(verifier, VT_STRCOLS) &&
           verifier.VerifyVector(strcols()) &&
           verifier.VerifyVectorOfStrings(strcols()) &&
           verifier.EndTable();
  }
};

struct FbRowBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_numcols(flatbuffers::Offset<flatbuffers::Vector<int32_t>> numcols) {
    fbb_.AddOffset(FbRow::VT_NUMCOLS, numcols);
  }
  void add_strcols(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> strcols) {
    fbb_.AddOffset(FbRow::VT_STRCOLS, strcols);
  }
  explicit FbRowBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  FbRowBuilder &operator=(const FbRowBuilder &);
  flatbuffers::Offset<FbRow> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<FbRow>(end);
    return o;
  }
};

inline flatbuffers::Offset<FbRow> CreateFbRow(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<int32_t>> numcols = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> strcols = 0) {
  FbRowBuilder builder_(_fbb);
  builder_.add_strcols(strcols);
  builder_.add_numcols(numcols);
  return builder_.Finish();
}

inline flatbuffers::Offset<FbRow> CreateFbRowDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<int32_t> *numcols = nullptr,
    const std::vector<flatbuffers::Offset<flatbuffers::String>> *strcols = nullptr) {
  auto numcols__ = numcols ? _fbb.CreateVector<int32_t>(*numcols) : 0;
  auto strcols__ = strcols ? _fbb.CreateVector<flatbuffers::Offset<flatbuffers::String>>(*strcols) : 0;
  return rocksdb::CreateFbRow(
      _fbb,
      numcols__,
      strcols__);
}

inline const rocksdb::FbRow *GetFbRow(const void *buf) {
  return flatbuffers::GetRoot<rocksdb::FbRow>(buf);
}

inline const rocksdb::FbRow *GetSizePrefixedFbRow(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<rocksdb::FbRow>(buf);
}

inline bool VerifyFbRowBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<rocksdb::FbRow>(nullptr);
}

inline bool VerifySizePrefixedFbRowBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<rocksdb::FbRow>(nullptr);
}

inline void FinishFbRowBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<rocksdb::FbRow> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedFbRowBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<rocksdb::FbRow> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace rocksdb

#endif  // FLATBUFFERS_GENERATED_ROW_ROCKSDB_H_
