// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ROWSTR_ROCKSDB_H_
#define FLATBUFFERS_GENERATED_ROWSTR_ROCKSDB_H_

#include "flatbuffers/flatbuffers.h"

namespace rocksdb {

struct FbRowStr;

struct FbRowStr FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_COL = 4
  };
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *col() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(VT_COL);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_COL) &&
           verifier.VerifyVector(col()) &&
           verifier.VerifyVectorOfStrings(col()) &&
           verifier.EndTable();
  }
};

struct FbRowStrBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_col(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> col) {
    fbb_.AddOffset(FbRowStr::VT_COL, col);
  }
  explicit FbRowStrBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  FbRowStrBuilder &operator=(const FbRowStrBuilder &);
  flatbuffers::Offset<FbRowStr> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<FbRowStr>(end);
    return o;
  }
};

inline flatbuffers::Offset<FbRowStr> CreateFbRowStr(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> col = 0) {
  FbRowStrBuilder builder_(_fbb);
  builder_.add_col(col);
  return builder_.Finish();
}

inline flatbuffers::Offset<FbRowStr> CreateFbRowStrDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<flatbuffers::String>> *col = nullptr) {
  auto col__ = col ? _fbb.CreateVector<flatbuffers::Offset<flatbuffers::String>>(*col) : 0;
  return rocksdb::CreateFbRowStr(
      _fbb,
      col__);
}

inline const rocksdb::FbRowStr *GetFbRowStr(const void *buf) {
  return flatbuffers::GetRoot<rocksdb::FbRowStr>(buf);
}

inline const rocksdb::FbRowStr *GetSizePrefixedFbRowStr(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<rocksdb::FbRowStr>(buf);
}

inline bool VerifyFbRowStrBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<rocksdb::FbRowStr>(nullptr);
}

inline bool VerifySizePrefixedFbRowStrBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<rocksdb::FbRowStr>(nullptr);
}

inline void FinishFbRowStrBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<rocksdb::FbRowStr> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedFbRowStrBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<rocksdb::FbRowStr> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace rocksdb

#endif  // FLATBUFFERS_GENERATED_ROWSTR_ROCKSDB_H_
